// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/layout/Banner.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    MousePos: typeof import('./src/components/MousePos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
