export const productList = [
  {
    id: 7,
    title: '定位检测',
    algorithmType: 2,
    desc: `在识别出物体的基础上精确给出物体的坐标和角度信息。`,
    scene: '主控电路板封装机、器人工业制造等场景。',
    feature: 'productCneter/7.png',
  },
  {
    id: 8,
    title: '缺陷检测',
    algorithmType: 2,
    desc: `主要是指的各类外观缺陷，常见的缺陷包括表面装配缺陷（如漏装、混料、错位、错色等)、
    表面印刷缺陷（如多印、漏印、重印、拉丝、模糊等)、表面形状缺陷（如崩边、披锋、凸起、凹坑、磨损等)。`,
    scene: '新能源电池外观缺陷检测、PCB电路板、半导体芯片表面、五金配件领域等场景。',
    feature: 'productCneter/8.png',
  },
  {
    id: 9,
    title: '识别判断',
    algorithmType: 2,
    desc: '对已知规律的物体进行分辨，包含外形、颜色、图案、数字、条码和二维码等。',
    feature: 'productCneter/9.png',
    scene: '工业产线、标签检测、产品标记、产品包装等场景。',
  },
  {
    id: 10,
    title: '测量测距',
    algorithmType: 2,
    desc: `把获取的图像像素信息标定成常用的度量衡单位，然后在图像中精确计算出需要知道的几何尺寸。
    通过图像的方式更容易测量一些组合复杂的尺寸或基准复杂的尺寸。`,
    scene: '电子元器件，汽车零部件，手机零部件，螺塑料、陶瓷等场景。',
    feature: 'productCneter/10.png',
  },
  {
    id: 11,
    title: '统计分拣',
    algorithmType: 2,
    desc: `判断生产线或转运场景下运动目标的类别和数量等信息，再配合机器人对货品进行分拣工作。`,
    scene: '工业、制造业领以及生产自动化领域等场景。',
    feature: 'productCneter/11.png',
  },
  {
    id: 1,
    title: '跌倒检测',
    algorithmType: 1,
    attitude: 1,
    desc: `通过室内外固定摄像头辅助判断老年人跌倒状态，实时多端异常状态同步（设备前端、管理终端、协管手机端等）预警，
    可针对预警信号调取现场视频进行二次确认并关联后续操作执行。利用智能化手段赋能于传统健康监护行业，应用于养老院、医院、家庭监护等场景。`,
    scene: '养老院、医院、家庭监护等场景。',
    feature: 'productCneter/1.png',
  },
  {
    id: 2,
    title: '教体训练考核',
    algorithmType: 1,
    attitude: 2,
    desc: `针对各类院校考试和训练场景，通过固定式检测设备或手机应用程序，可自动识别判断各项运动的动作是否规范标准，
    规避因人工考评导致的误判、漏判、作弊等问题，便于针对性地制定更精准有效的训练方案。检测动作包含：立定跳远、仰卧起坐、引体向上、俯卧撑等。`,
    scene: '立定跳远、仰卧起坐、引体向上、俯卧撑。',
    feature: 'productCneter/2.png',
  },
  {
    id: 3,
    title: '儿童坐姿校准',
    algorithmType: 1,
    attitude: 2,
    desc: `通过桌面台灯集成摄像头方式实时检测、判断被检区域内人员坐姿是否标准，
    如低头或者身体偏斜，会有效地检测这种坐姿偏移的情况，并配备同步语音提示功能，有助预防青少年近视。`,
    scene: '写作业、看书等场景。',
    feature: 'productCneter/3.png',
  },
  {
    id: 4,
    title: '手势识别',
    algorithmType: 1,
    attitude: 1,
    desc: `可识别常见的手势包括握拳、五指张开、竖食指、比心、点赞等。`,
    scene: '消费、娱乐、工业控制等场景。',
    feature: 'productCneter/4.png',
  },
  {
    id: 5,
    title: '动作检测',
    algorithmType: 1,
    attitude: 1,
    desc: `支持固定和移动部署，检测图面中所有人体，并标定坐标位置及各部位关节点，
    对应不同关节点的组合变化进行动作识别判断，可应用于违规、危险等动作判断。`,
    scene: '违规、危险等动作判断等场景。',
    feature: 'productCneter/5.png',
  },
  {
    id: 6,
    title: '运动姿态校准',
    algorithmType: 1,
    attitude: 2,
    desc: `通过镜面固定摄像头，判断镜前运动者身体各部位对应标准动作姿态的准确度，并在镜面同步展示标准动作与运动者动作关节点的角度偏差值，
    以便进行实时校准。赋能居家运动、健身镜、瑜伽等场景。`,
    scene: '赋能居家运动、健身镜、瑜伽等场景。',
    feature: 'productCneter/6.png',
  },
  {
    id: 17,
    title: '移动人形',
    algorithmType: 4,
    desc: `可以实现移动人形检测、人形坐标、人形姿态的功能。 实时给出人体头、肩、腰、腿等位置， 可适用于各种大幅度人体动作。`,
    scene: '家庭、公司、店铺、小区、智慧商城等场景。',
    feature: 'productCneter/17.png',
  },
  {
    id: 18,
    title: '宠物跟踪',
    algorithmType: 4,
    desc: `宠物追踪器可实时监控宠物们的健康、可通过宠物的专属运动算法，有效获取宠物的运动、睡眠数据，提示宠物的健康状态。`,
    scene: '宠物看护、宠物陪伴、宠物跟踪抓拍等场景。',
    feature: 'productCneter/18.png',
  },
  {
    id: 12,
    title: '人脸识别',
    algorithmType: 3,
    desc: '给定目标人脸，从人脸库中找到最相似的一张或多张人脸，并返回人脸相似度分数。可满足人脸考勤机人脸识别通行等应用场景。',
    scene: '人脸实名认证、人脸考勤、人脸闸机、人脸搜索。',
    feature: 'productCneter/12.png',
  },
  {
    id: 13,
    title: '物体识别',
    algorithmType: 3,
    desc: `标签丰富 提供精确的大流量服务。支持毫秒级的识别响应能力、弹性灵活的高并发。`,
    scene: '智能相册、拍照识图等场景。',
    feature: 'productCneter/13.png',
  },
  {
    id: 14,
    title: '车牌识别',
    algorithmType: 3,
    desc: `利用大量的车牌数据和先进的图像处理能力， 支持识别多种常见类型车牌信息， 对蓝牌、绿牌、单黄牌识别准确率可达95%以上。`,
    scene: '车辆进出场、道路违章等场景。',
    feature: 'productCneter/14.png',
  },
  {
    id: 15,
    title: '宠物识别',
    algorithmType: 3,
    desc: `检测图像中出现的猫狗，接口返回宠物位置和宠物类别。`,
    scene: '检测猫狗的类别等场景。',
    feature: 'productCneter/15.png',
  },
  {
    id: 16,
    title: 'OCR识别',
    algorithmType: 3,
    desc: '可准确识别图片中的二维码、条形码信息，提供企业级稳定、精确的大流量服务。',
    scene: '智慧教育、智慧校园等场景。',
    feature: 'productCneter/16.png',
  },
]
